### ISSUE TITLE
Releasing is broken in `cdk-from-cfn`

### ISSUE THREAD

**Issue by rix0rrr** [cdklabs/cdk-from-cfn#739]

**Comment by iph** [comment]
One thing that's a bit confusing is that there is a cross-release in `cdk-from-cfn`. 

1. it attempts to publish to Rust. One thing that Kendra and I discussed a while ago was deprecating the Rust release. I'm personally okay with this, because the current form of the library needs to be redone entirely and is not consumable as a Library today.
2. It releases to NPM using some web-asm shenanigans. I assume this is how the CDK team picks up the package. 

Personally, I would prefer we just nuke: https://github.com/cdklabs/cdk-from-cfn/blob/main/.github/workflows/release.yml#L10-L53 .


I have a grander vision for this package. The current Rust implementation has a lot of reusable bits that are unfortunately heavily tied to the one implementation. I want to rewrite the core and break it into pieces. Then one day publish:
- Core CFN parsing (parser/ + a little ir/)
- CFN Spec parsing
- <CDK-From-CFN> that reads from cfn parsing and spec parsing, and produces the spec itself. 
   - This would hold the output library transforms and a split in the IR -- we would split anything that doesn't rely on CFN Specification, and move that to the parser (e.g. Fn::Sub), and anything that relies on CFN Specification remains in `cdk-from-cfn`. 

My intent is to create 2 projects in the future, which require both spec parsing, and cfn parsing. Both need parsing and spec parsing, but neither need the current uses that cdk-from-cfn uses. 

But as to this issue, yeah, let's just nuke the Rust bits -- the Rust code is not reusable and can just be built from source.

**Comment by rix0rrr** [comment]
That sounds good. It's natural to first build something useful and then find that there's a useful core to be extracted At A Later Date 😉 . I feel the same about the CloudFormation bits in the CDK CLI.

I'll just try to make this work first; you can decide later on whether you want to turn this repo into a monorepo, keeping all the code here, or if you want to extract to a separate repo.
